favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://IMG_0003.jpeg'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
