_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 83d8ce76-9d91-4f65-9040-9123d57daee0
name: 'Drupal Practice'
mail: admin@example.com
slogan: 'Awesome platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
